REPORT  ZSIMPLE_DBPRG.

TABLES MARA.

DATA : WA_MARA LIKE MARA.
START-OF-SELECTION.

**FIRST MARA IS DATABASE TABLE SECOND MARA IS DEFAULT STRUCTURE

*SELECT SINGLE * FROM MARA INTO MARA.

*  SELECT SINGLE * FROM MARA INTO MARA WHERE matnr EQ ‘000000000000000023’.

SELECT SINGLE * FROM MARA INTO MARA WHERE matnr EQ ‘000000000000000023’.

IF SY-SUBRC EQ 0.

WRITE :/10 ‘SELECT SUCCESSFUL’.

move-CORRESPONDING mara to wa_mara.

ELSE.

WRITE :/10 ‘SELECT NOT SUCCESSFUL’.

ENDIF.

END-OF-SELECTION.

if WA_mara is not INITIAL.

WRITE /10 : WA_MARA-MATNR,  “MATERIAL NUMBER

WA_MARA-MTART,  “MATERIAL TYPE

WA_MARA-MBRSH,  “INDUSTRY SECTOR

WA_MARA-MATKL.  “MATERIAL ID

else.

write :/10 ‘wa_mara is empty…’.

endif.
